### ISSUE TITLE
翻译 30-day-warranty

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/open-source-camp#17]
## 任务必读
- [翻译任务汇总](https://github.com/WillemJiang/open-source-camp/issues/16)
- [Markdown 格式语法](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** 30 Day Warranty
* **原文链接：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/patterns/2-structured/30-day-warranty.md
* **提交路径：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/patterns/30-day-warranty.md
* **翻译收益：** 熟悉翻译流程
* **翻译难度：** 容易

## 翻译人员
@WillemJiang

**Comment by WillemJiang** [comment]
翻译稿已经提交
https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/30-day-warranty.md

欢迎大家帮忙校对。

**Comment by anzipomelo** [comment]
认领校对

**Comment by anzipomelo** [comment]
> 翻译稿已经提交 https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/30-day-warranty.md
> 
> 欢迎大家帮忙校对。

链接打不开了，404

**Comment by WillemJiang** [comment]
sorry 链接贴错了 https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/patterns/30-day-warranty.md

**Comment by WillemJiang** [comment]
翻译已经合入主干。
