### ISSUE TITLE
翻译 Trusted Committer Pattern

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/open-source-camp#18]
## 任务必读
- [翻译任务汇总](https://github.com/WillemJiang/open-source-camp/issues/16)
- [Markdown 格式语法](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** Trusted Committer
* **原文链接：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/patterns/2-structured/trusted-committer.md
* **提交路径：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/patterns/trusted-committer.md
* **翻译收益：**
* **翻译难度：**  中等

## 翻译人员
@WillemJiang 

## 校对人员
@hncslwx

**Comment by hncslwx** [comment]
我领这个pattern的翻译

**Comment by WillemJiang** [comment]
@hncslwx 这部分的翻译已经做完，麻烦校对一下相关的PR https://github.com/WillemJiang/InnerSourcePatterns/pull/1
