### ISSUE TITLE
翻译贡献者模版

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/open-source-camp#19]
## 任务必读
- [翻译任务汇总](https://github.com/WillemJiang/open-source-camp/issues/16)
- [Markdown 格式语法](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** CONTRIBUTING-template
* **原文链接：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/patterns/2-structured/project-setup/templates/CONTRIBUTING-template.md
* **提交路径：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/templates/CONTRIBUTING-template.md
* **翻译收益：**  了解内源贡献者文档模版
* **翻译难度：** 中

**Comment by gzchenyong** [comment]
认领该任务
