### ISSUE TITLE
翻译 README 模版

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/open-source-camp#20]
## 任务必读
- [翻译任务汇总](https://github.com/WillemJiang/open-source-camp/issues/16)
- [Markdown 格式语法](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** README-template.md
* **原文链接：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/patterns/2-structured/project-setup/templates/README-template.md
* **提交路径：** https://github.com/WillemJiang/InnerSourcePatterns/blob/translation-cn/translation/cn/templates/README-template.md
* **翻译收益：** 了解内源项目README 模版内容
* **翻译难度：** 中

**Comment by hncslwx** [comment]
我领readme
